### ISSUE TITLE
Could not pass event PlayerInteractEvent to CreativeItemControl

### ISSUE THREAD

**Issue by mibby** [Brokkonaut/Bukkit-CreativeItemControl#4]
CreativeItemControl dev 38

```
[05:56:03] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CreativeItemControl v1.16-SNAPSHOT-brokko
java.lang.ArrayIndexOutOfBoundsException: Index 12 out of bounds for length 12
	at org.cyberiantiger.minecraft.unsafe.v1_16_R1.NBTTools.fromNativeCompound(NBTTools.java:177) ~[?:?]
	at org.cyberiantiger.minecraft.unsafe.v1_16_R1.NBTTools.fromNativeCompound(NBTTools.java:185) ~[?:?]
	at org.cyberiantiger.minecraft.unsafe.v1_16_R1.NBTTools.fromNativeCompound(NBTTools.java:185) ~[?:?]
	at org.cyberiantiger.minecraft.unsafe.v1_16_R1.NBTTools.readItemStack(NBTTools.java:336) ~[?:?]
	at org.cyberiantiger.minecraft.itemcontrol.Main.onPlayerInteract(Main.java:330) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor211.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:492) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1462) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1191) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1184) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1160) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Tuinity-"10d9b1f"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by Brokkonaut** [comment]
Should be fixed in build 39

**Comment by mibby** [comment]
Seems to be fixed, thanks.
