### ISSUE TITLE
1.16.2 Compatibility

### ISSUE THREAD

**Issue by mibby** [Brokkonaut/Bukkit-CreativeItemControl#5]
```
[09:14:52] [Server thread/INFO]: [CreativeItemControl] Enabling CreativeItemControl v1.16-SNAPSHOT-brokko
[09:14:52] [Server thread/ERROR]: Error occurred while enabling CreativeItemControl v1.16-SNAPSHOT-brokko (Is it up to date?)
java.lang.UnsupportedOperationException: Unsupported CraftBukkit version: 1.16.2-R0.1-SNAPSHOT
	at org.cyberiantiger.minecraft.unsafe.CBShim.unsupportedVersion(CBShim.java:121) ~[?:?]
	at org.cyberiantiger.minecraft.unsafe.CBShim.createShim(CBShim.java:49) ~[?:?]
	at org.cyberiantiger.minecraft.itemcontrol.Main.onEnable(Main.java:158) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:242) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassNotFoundException: org.cyberiantiger.minecraft.unsafe.v1_16_R2.NBTTools
	at java.net.URLClassLoader.findClass(URLClassLoader.java:435) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:340) ~[?:?]
	at org.cyberiantiger.minecraft.unsafe.CBShim.loadShim(CBShim.java:100) ~[?:?]
	at org.cyberiantiger.minecraft.unsafe.CBShim.createShim(CBShim.java:44) ~[?:?]
	... 11 more
[09:14:52] [Server thread/INFO]: [CreativeItemControl] Disabling CreativeItemControl v1.16-SNAPSHOT-brokko
```

**Comment by Brokkonaut** [comment]
Please try the latest dev build from https://www.iani.de/jenkins/job/Bukkit-CreativeItemControl/

**Comment by mibby** [comment]
Seems fixed, thanks.
